# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-10-02 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goods_usingby'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': '电脑', 'verbose_name_plural': '电脑'},
        ),
        migrations.AlterModelOptions(
            name='goodscategory',
            options={'verbose_name': '电脑类别', 'verbose_name_plural': '电脑类别'},
        ),
        migrations.AlterModelOptions(
            name='goodsimage',
            options={'verbose_name': '电脑图片', 'verbose_name_plural': '电脑图片'},
        ),
        migrations.RemoveField(
            model_name='goods',
            name='goods_desc',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='goods_num',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='usingby',
        ),
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategory', verbose_name='电脑类目'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_brief',
            field=models.TextField(max_length=500, verbose_name='电脑简短描述'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_sn',
            field=models.CharField(default='', max_length=50, verbose_name='电脑唯一货号'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(max_length=100, verbose_name='电脑名'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='sold_num',
            field=models.IntegerField(default=0, verbose_name='电脑销售量'),
        ),
        migrations.AlterField(
            model_name='goodscategorybrand',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='goods.GoodsCategory', verbose_name='物品类目'),
        ),
        migrations.AlterField(
            model_name='goodsimage',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.Goods', verbose_name='电脑'),
        ),
    ]
