# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-10-02 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20201002_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategoryBrand', verbose_name='电脑品牌'),
        ),
        migrations.AlterField(
            model_name='goodscategorybrand',
            name='name',
            field=models.CharField(blank=True, default='', help_text='品牌名', max_length=30, null=True, verbose_name='品牌名'),
        ),
    ]
