# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-10-02 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20201002_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='sold_num',
        ),
        migrations.RemoveField(
            model_name='goodscategory',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='goodscategorybrand',
            name='desc',
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_sn',
            field=models.CharField(default='', max_length=50, verbose_name='电脑唯一SN号'),
        ),
    ]
