# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-10-03 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20201003_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodscategorybrand',
            name='image',
        ),
    ]
