# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-10-03 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0003_auto_20201003_1951'),
        ('goods', '0007_remove_goodscategorybrand_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='market_price',
        ),
        migrations.AddField(
            model_name='goods',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_operation.Employee', verbose_name='使用教师'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='是否正在使用'),
        ),
    ]
