# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-10-03 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_goods_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodscategorybrand',
            name='brand_image',
            field=models.ImageField(blank=True, null=True, upload_to='brand/images/', verbose_name='实物图'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_front_image',
            field=models.ImageField(blank=True, null=True, upload_to='goods/images/', verbose_name='协议书'),
        ),
    ]
