# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-10-14 08:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0011_auto_20201003_2345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodscategorybrand',
            options={'verbose_name': '品牌'},
        ),
        migrations.RemoveField(
            model_name='goodscategory',
            name='category_type',
        ),
        migrations.AlterModelTable(
            name='goodscategorybrand',
            table=None,
        ),
    ]
