# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-10-14 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0012_auto_20201014_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodscategory',
            name='category_type',
            field=models.IntegerField(blank=True, choices=[(1, '台式机'), (1, '笔记本电脑'), (1, '平板电脑'), (1, '路由器'), (1, '交换机'), (1, '其他')], help_text='类目级别', null=True, verbose_name='类目级别'),
        ),
    ]
