# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-10-03 14:23
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0005_auto_20201002_1456'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('contract_image', models.ImageField(blank=True, null=True, upload_to='user_operation/images/', verbose_name='协议书')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('goods', models.ForeignKey(help_text='电脑SN', on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='电脑')),
            ],
            options={
                'verbose_name': '使用登记',
                'verbose_name_plural': '使用登记',
            },
        ),
        migrations.AlterUniqueTogether(
            name='userfav',
            unique_together=set([('employee', 'goods')]),
        ),
    ]
