# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-10-03 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0002_auto_20201003_1426'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfav',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='userfav',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='userfav',
            name='goods',
        ),
        migrations.DeleteModel(
            name='UserFav',
        ),
    ]
