# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-10-03 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0003_auto_20201003_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(default='', help_text='教师名', max_length=30, unique=True, verbose_name='教师名'),
        ),
    ]
