# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-10-03 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0004_auto_20201003_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='电话号码', max_length=11, null=True, verbose_name='电话号码'),
        ),
    ]
