# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-10-03 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0006_auto_20201003_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='office',
            options={'verbose_name': '处室', 'verbose_name_plural': '处室'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='office',
        ),
    ]
