# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-10-13 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0007_auto_20201003_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='phone',
        ),
    ]
